/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 -k /Users/ajdemarco/Desktop/E-Flex Digital/mushroom-labratory/BakedIsland.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/BakedIsland.glb')
  return (
    <group scale={20} position={[0,-7.5, 0]} {...props} dispose={null}>
      <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials.Top} />
      <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials.Body} />
    </group>
  )
}

useGLTF.preload('/BakedIsland.glb')
